version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nestjs-api
permissions:
  - object: /home/ubuntu/nestjs-api
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
