version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Pre-build steps"
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - echo "Build completed on `date`"
      - echo "Listing contents of dist directory"
      - ls -la dist
      - echo "Listing contents of current directory"
      - ls -la
      - rm -rf node_modules
      - echo "Zipping dist directory"
      - zip -r buildProject.zip dist
  post_build:
    commands:
      - echo "Post-build steps"
      - aws s3 cp buildProject.zip s3://my-nest-project-44444/test

artifacts:
  files:
    - '**/*'
  name: buildProject.zip
  discard-paths: no
