name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

     env:  
      DB_HOST: database-1.crmqwukkkrmp.us-east-1.rds.amazonaws.com
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      DB_TYPE: postgres
      DB_PORT: 5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:e2e
